### ISSUE TITLE
Step exits before copying artifacts

### ISSUE THREAD

**Issue by 0xgivn** [kimdv/bitrise-step-swiftlint#16]
If we set the mode to strict and linting fails, the script exits before having the chance to copy the report to `SWIFTLINT_REPORT_PATH`. 
This obfuscates the results and doesn't provide clear feedback to developers what went wrong.

**Comment by 0xgivn** [comment]
I have prepared a branch with a fix + one other minor fix. Unfortunately I don't have permissions to push it and make a pull request.

**Comment by kimdv** [comment]
Hi @georgiIvanov  👋

> I have prepared a branch with a fix + one other minor fix. Unfortunately I don't have permissions to push it and make a pull request.

You need to fork, and then push to your fork. 
After that you are able to make a PR 👍

If there is any questions, feel free to ask

**Comment by 0xgivn** [comment]
Issue fixed in [PR](https://github.com/kimdv/bitrise-step-swiftlint/pull/17)
