### ISSUE TITLE
Ignores custom configuration file

### ISSUE THREAD

**Issue by vojtechvrbka** [kimdv/bitrise-step-swiftlint#2]
I set `Linting configuration file` in `Options` section, but it ignores the configuration file.

My config's file name is `swiftlint.yml`

Log:
````
INFO[08:09:27]  * [OK] Step dependency (swiftlint) installed, available. 
+ '[' -z /Users/vagrant/git ']'
+ cd /Users/vagrant/git
+ '[' -z /Users/vagrant/git/swiftlint.yml ']'
+ swiftlint lint --reporter xcode
Loading configuration from '.swiftlint.yml'
````

**Comment by kimdv** [comment]
Hello @vojtechvrbka ! 

I have made a pull request, that should solve the problem! :)
https://github.com/bitrise-io/bitrise-steplib/pull/1217

**Comment by kimdv** [comment]
Hi @vojtechvrbka 

Have you tried the new update?
Did it work?? 😄

**Comment by vojtechvrbka** [comment]
Yes It works now, thank you
