### ISSUE TITLE
 bitrise-step-swiftlint isn’t synced with Bitrise Swiftlint module

### ISSUE THREAD

**Issue by 22Round** [kimdv/bitrise-step-swiftlint#21]
When I added swiftlint module to Bitrise workflow, I mentioned that versions isn’t synced.
In workflow it shows 0.8 and on git most recent is 0.10.0.
How we can fix this? 
<img width="698" alt="Screenshot 2023-01-06 at 18 32 06" src="https://user-images.githubusercontent.com/5682469/211163487-2c89e649-c293-412f-8efc-2fa831006761.png">

**Comment by kimdv** [comment]
https://github.com/bitrise-io/bitrise-steplib/pull/3708

**Comment by kimdv** [comment]
It's merged and should be available.
