### ISSUE TITLE
How can I configure output as swiftlint result as variable

### ISSUE THREAD

**Issue by y8k** [kimdv/bitrise-step-swiftlint#6]
I added variable for swliftlint result in shell script code.
But I can't understand how can I output to bind variable to `outputs:` in `step.yml`
Could you explain step by step to configure output?

**Comment by kimdv** [comment]
Hi! 

Hmm... I don't think there is anything to the `output`. 
But we could add something. 

But, all the lint should be printed in the terminal.

**Comment by y8k** [comment]
I want to output to slack or github comment like as danger. So I ask to
you. please consider output as lint result..

2019년 5월 31일 (금) 오후 8:37, Kim de Vos <notifications@github.com>님이 작성:

**Comment by lawicko** [comment]
I think having some kind of output here would be really great. My usage scenario is this:
- This step is part of my workflow for the new merge requests on GitLab
- when the new MR is created, the pipeline starts and it breaks when this step fails (errors are generate)

Now, this all works fine, however if the failure happens, the way to get to the actual information on what failed is anything but easy. I have to go to the build log on Bitrise and find the step output in the console log. The better way to do it, in my opinion, is to generate a html report and put it in the artifacts section. I think if this step generates some output, that would be possible to do.

**Comment by kimdv** [comment]
As default SwiftLint don't create files: https://github.com/realm/SwiftLint/issues/2977

But feel free to open a PR here and I will look at it

**Comment by lawicko** [comment]
Sure, I was rather thinking of having the SwiftLint output in a variable, which can later be used by other steps to publish it somewhere, for example in a Bitrise deploy step etc.

**Comment by kimdv** [comment]
Fixed in https://github.com/bitrise-io/bitrise-steplib/pull/2464#event-3303753004
