### ISSUE TITLE
The new lint_range property causes the step to fail silently

### ISSUE THREAD

**Issue by lawicko** [kimdv/bitrise-step-swiftlint#8]
The new `lint_range` property is defined as `required`, but it doesn't have a default value set in the `.yml` and if it is undefined, it just fails the linting silently.

I just stumbled upon this while working on something else, I fear that when users on Bitrise update to the new version, it's going to fail silently for everybody.

Funny thing is, the default value was originally there, but for some reason it was removed in [this commit](https://github.com/kimdv/bitrise-step-swiftlint/commit/2735bb3d2794ab1fbe261c8cf14be158d4db04bf).

**Comment by kimdv** [comment]
Fixed in https://github.com/kimdv/bitrise-step-swiftlint/commit/f2849ef21d37271edb649fcc8f00cd13b5b0f460
