### ISSUE TITLE
When using lint_range only the first linting error will be reported

### ISSUE THREAD

**Issue by lawicko** [kimdv/bitrise-step-swiftlint#9]
I may be wrong with this one, but when I think that because of this:
`set -ex`
the script will exit when it encounters an error. So, when reading line by line using the `lint_range` like so:
```
git diff --name-only | while read filename; do run_swiftlint "${filename}" "${reporter}" "${FLAGS}"; done
git diff --cached --name-only | while read filename; do run_swiftlint "${filename}" "${FLAGS}"; done
```
 it's gonna exit on the first line with an error. So only one error maximum can be printed to the console at a time, right? Btw. why do we have 2 loops here? Sorry if this is a noob question but bash is not my native language ;)

**Comment by kimdv** [comment]
Fixed in https://github.com/bitrise-io/bitrise-steplib/pull/2464#event-3303753004
